import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import type { Metadata } from "next";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";
import { Vazirmatn } from "next/font/google";

const vazirmatn = Vazirmatn({
  subsets: ["arabic"],
  variable: "--font-vazirmatn",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={vazirmatn.variable}>
        <Theme className="bg-neutral text-sm">
          <NavBar />
          <main>{children}</main>
        </Theme>
      </body>
    </html>
  );
}
